import 'package:flutter/material.dart';
import '../generatediphone11prox2widget/generated/GeneratedRectangle1Widget.dart';
import '../generatediphone11prox2widget/generated/GeneratedImage10Widget.dart';
import '../generatediphone11prox2widget/generated/GeneratedImage1Widget.dart';
import '../generatediphone11prox2widget/generated/GeneratedSIGNINWITHFACEBOOKWidget.dart';
import '../generatediphone11prox2widget/generated/GeneratedPapers1Widget1.dart';
import '../generatediphone11prox2widget/generated/GeneratedImage3Widget.dart';
import '../generatediphone11prox2widget/generated/GeneratedRectangle3Widget1.dart';
import '../generatediphone11prox2widget/generated/GeneratedSIGNINWITHGOOGLEWidget.dart';
import '../generatediphone11prox2widget/generated/GeneratedLine1Widget.dart';
import '../generatediphone11prox2widget/generated/GeneratedSIGNINWidget.dart';
import '../generatediphone11prox2widget/generated/GeneratedPasswordWidget.dart';
import '../generatediphone11prox2widget/generated/GeneratedEnteryourdetailsWidget.dart';
import '../generatediphone11prox2widget/generated/GeneratedRectangle2Widget1.dart';
import '../generatediphone11prox2widget/generated/GeneratedRectangle4Widget.dart';
import '../generatediphone11prox2widget/generated/GeneratedEmailorusernameWidget.dart';

/* Frame iPhone 11 Pro / X - 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.000732421875,
                child: GeneratedPapers1Widget1(),
              ),
              Positioned(
                left: 30.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 122.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 75.0,
                top: 93.0,
                right: null,
                bottom: null,
                width: 216.0,
                height: 26.0,
                child: GeneratedEnteryourdetailsWidget(),
              ),
              Positioned(
                left: 31.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 43.0,
                top: 152.0,
                right: null,
                bottom: null,
                width: 150.0,
                height: 23.0,
                child: GeneratedEmailorusernameWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 213.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 28.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 265.0,
                right: null,
                bottom: null,
                width: 269.0,
                height: 47.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 142.0,
                top: 279.0,
                right: null,
                bottom: null,
                width: 94.0,
                height: 22.0,
                child: GeneratedSIGNINWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 53.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 37.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 29.0,
                child: GeneratedSIGNINWITHGOOGLEWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 596.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 53.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 37.0,
                top: 611.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 29.0,
                child: GeneratedSIGNINWITHFACEBOOKWidget(),
              ),
              Positioned(
                left: 284.0,
                top: 528.0,
                right: null,
                bottom: null,
                width: 28.0,
                height: 27.0,
                child: GeneratedImage1Widget(),
              ),
              Positioned(
                left: 284.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 29.0,
                height: 32.41176223754883,
                child: GeneratedImage3Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 27.0,
                child: GeneratedImage10Widget(),
              )
            ]),
      ),
    ));
  }
}
