import 'package:flutter/material.dart';
import '../generatediphone11prox5widget/generated/GeneratedQuicksortWidget.dart';
import '../generatediphone11prox5widget/generated/GeneratedInsertsortWidget.dart';
import '../generatediphone11prox5widget/generated/GeneratedPapers1Widget3.dart';
import '../generatediphone11prox5widget/generated/GeneratedEllipse6Widget.dart';
import '../generatediphone11prox5widget/generated/GeneratedBinarysearchWidget.dart';
import '../generatediphone11prox5widget/generated/GeneratedEllipse4Widget.dart';
import '../generatediphone11prox5widget/generated/GeneratedEllipse2Widget1.dart';
import '../generatediphone11prox5widget/generated/GeneratedEllipse5Widget.dart';
import '../generatediphone11prox5widget/generated/GeneratedBubblesortWidget.dart';
import '../generatediphone11prox5widget/generated/GeneratedEllipse3Widget.dart';
import '../generatediphone11prox5widget/generated/GeneratedImage10Widget2.dart';

/* Frame iPhone 11 Pro / X - 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.000732421875,
                child: GeneratedPapers1Widget3(),
              ),
              Positioned(
                left: 23.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 160.0,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: 23.0,
                top: 55.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 160.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 183.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 160.0,
                child: GeneratedEllipse4Widget(),
              ),
              Positioned(
                left: 188.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 160.0,
                child: GeneratedEllipse5Widget(),
              ),
              Positioned(
                left: 23.0,
                top: 422.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 160.0,
                child: GeneratedEllipse6Widget(),
              ),
              Positioned(
                left: 52.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 79.0,
                child: GeneratedBubblesortWidget(),
              ),
              Positioned(
                left: 211.0,
                top: 275.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 79.0,
                child: GeneratedInsertsortWidget(),
              ),
              Positioned(
                left: 36.0,
                top: 478.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 53.0,
                child: GeneratedQuicksortWidget(),
              ),
              Positioned(
                left: 219.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 109.0,
                height: 81.0,
                child: GeneratedBinarysearchWidget(),
              ),
              Positioned(
                left: 8.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 27.0,
                child: GeneratedImage10Widget2(),
              )
            ]),
      ),
    ));
  }
}
