import 'package:flutter/material.dart';
import '../generatediphone11prox8widget/generated/GeneratedImage10Widget5.dart';
import 'generated/GeneratedBubbleSortSim.dart';

/* Frame iPhone 11 Pro / X - 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.000732421875,
                child: BubbleSortSimulation(),
              ),
              Positioned(
                left: 8.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 27.0,
                child: GeneratedImage10Widget5(),
              )
            ]),
      ),
    ));
  }
}
