import 'package:flutter/material.dart';

/* Rectangle image 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 320.0,
      height: 252.0,
    ));
  }
}
