import 'package:flutter/material.dart';
import '../generatediphone11prox1widget/generated/GeneratedWelcometoAlgolandWidget.dart';
import '../generatediphone11prox1widget/generated/GeneratedGETSTARTEDWidget.dart';
import '../generatediphone11prox1widget/generated/GeneratedExperientiallearningofalgorithmsWidget.dart';
import '../generatediphone11prox1widget/generated/GeneratedRectangle3Widget.dart';
import '../../helpers/transform/transform.dart';
import '../generatediphone11prox1widget/generated/GeneratedRectangle2Widget.dart';
import '../generatediphone11prox1widget/generated/GeneratedPapers1Widget.dart';
import '../generatediphone11prox1widget/generated/GeneratedIALREADYHAVEANACCOUNTWidget.dart';

/* Frame iPhone 11 Pro / X - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.000732421875,
                child: GeneratedPapers1Widget(),
              ),
              Positioned(
                left: null,
                top: null,
                right: null,
                bottom: null,
                width: 303.0,
                height: 97.0,
                child: TransformHelper.translate(
                    x: 1.00,
                    y: -164.50,
                    z: 0,
                    child: GeneratedWelcometoAlgolandWidget()),
              ),
              Positioned(
                left: 4.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 363.0,
                height: 34.0,
                child: GeneratedExperientiallearningofalgorithmsWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 643.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 47.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 126.0,
                top: 656.0,
                right: null,
                bottom: null,
                width: 125.0,
                height: 25.0,
                child: GeneratedGETSTARTEDWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 698.0,
                right: null,
                bottom: null,
                width: 332.0,
                height: 47.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 38.0,
                top: 711.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 25.0,
                child: GeneratedIALREADYHAVEANACCOUNTWidget(),
              )
            ]),
      ),
    ));
  }
}
