import 'package:flutter/material.dart';
import '../generatediphone11prox4widget/generated/GeneratedPapers1Widget2.dart';
import '../generatediphone11prox4widget/generated/GeneratedImage5Widget.dart';
import '../generatediphone11prox4widget/generated/GeneratedGroupWidget.dart';
import '../generatediphone11prox4widget/generated/GeneratedGroupWidget2.dart';
import '../generatediphone11prox4widget/generated/GeneratedGroupWidget1.dart';
import '../generatediphone11prox4widget/generated/GeneratedImage4Widget.dart';
import '../generatediphone11prox4widget/generated/GeneratedImage10Widget1.dart';
import '../generatediphone11prox4widget/generated/GeneratedEllipse1Widget.dart';
import '../generatediphone11prox4widget/generated/GeneratedImage6Widget.dart';
import '../generatediphone11prox4widget/generated/GeneratedEllipse2Widget.dart';

/* Frame iPhone 11 Pro / X - 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone11ProX4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.000732421875,
                child: GeneratedPapers1Widget2(),
              ),
              Positioned(
                left: 133.0,
                top: 357.0,
                right: null,
                bottom: null,
                width: 89.0,
                height: 90.0,
                child: GeneratedImage5Widget(),
              ),
              Positioned(
                left: 130.0,
                top: 172.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 88.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 132.0,
                top: 173.0,
                right: null,
                bottom: null,
                width: 83.0,
                height: 82.0,
                child: GeneratedImage4Widget(),
              ),
              Positioned(
                left: 133.0,
                top: 555.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 88.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 152.0,
                top: 570.0,
                right: null,
                bottom: null,
                width: 55.0,
                height: 57.0,
                child: GeneratedImage6Widget(),
              ),
              Positioned(
                left: 74.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 211.57626342773438,
                height: 49.97322082519531,
                child: GeneratedGroupWidget(),
              ),
              Positioned(
                left: 123.0,
                top: 447.0,
                right: null,
                bottom: null,
                width: 104.19464111328125,
                height: 38.836036682128906,
                child: GeneratedGroupWidget1(),
              ),
              Positioned(
                left: 81.0,
                top: 627.0,
                right: null,
                bottom: null,
                width: 193.81483459472656,
                height: 47.56172561645508,
                child: GeneratedGroupWidget2(),
              ),
              Positioned(
                left: 8.0,
                top: 16.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 27.0,
                child: GeneratedImage10Widget1(),
              )
            ]),
      ),
    ));
  }
}
