import 'package:flutter/material.dart';

/* Rectangle image 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedImage9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 675.0,
      height: 418.0,
    ));
  }
}
